[package]
name = "rust_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = { version="3.3.0", features=["optional_eip3607"]}
ethers = "2.0.4"
ethers-core = "2.0.4"
ethers-contract = "2.0.4"
primitive-types = "0.12.1"
hex = "0.4.3"
serde_json = "1.0.96"
ethabi = "18.0.0"
kdam = "0.3.0"
bytes = "1.4.0"
csv = "1.2.2"
fastrand = "2.0.0"
hashbrown = "0.13.2"
log = "0.4.19"
