name: code-formatting
run-name: ${{ github.actor }} code format checks
on: [pull_request]
jobs:
  python_linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install hatch
      - run: hatch run dev:lint
  rust_linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
  rust_clippy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -Dwarnings
