name: Main

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release from main
        if: github.ref == 'refs/heads/main'
        steps:
          - run: echo HELLO
      - name: No release
        if: github.ref != 'refs/heads/main'
        steps:
          - run: echo '::warning ::Release can only be run from the main branch!'
